// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRTIEvvpjFf2jJjjdT5NtV0MJHXswoaeg',
    appId: '1:274084305161:web:517fc6de342f2c710a5bd8',
    messagingSenderId: '274084305161',
    projectId: 'bookswap-c8bb5',
    authDomain: 'bookswap-c8bb5.firebaseapp.com',
    storageBucket: 'bookswap-c8bb5.firebasestorage.app',
    measurementId: 'G-LREBBTNRQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDaSgvaIAdnqfcdJ2tCyaw-mhCInjf3EY',
    appId: '1:274084305161:android:684e1d6b8e9b087d0a5bd8',
    messagingSenderId: '274084305161',
    projectId: 'bookswap-c8bb5',
    storageBucket: 'bookswap-c8bb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLt5LL__zbm_zFTfHf-HiEFuNdOU_6mAc',
    appId: '1:274084305161:ios:1d2cc3ad8ce31ada0a5bd8',
    messagingSenderId: '274084305161',
    projectId: 'bookswap-c8bb5',
    storageBucket: 'bookswap-c8bb5.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLt5LL__zbm_zFTfHf-HiEFuNdOU_6mAc',
    appId: '1:274084305161:ios:1d2cc3ad8ce31ada0a5bd8',
    messagingSenderId: '274084305161',
    projectId: 'bookswap-c8bb5',
    storageBucket: 'bookswap-c8bb5.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRTIEvvpjFf2jJjjdT5NtV0MJHXswoaeg',
    appId: '1:274084305161:web:697488dac772fbcf0a5bd8',
    messagingSenderId: '274084305161',
    projectId: 'bookswap-c8bb5',
    authDomain: 'bookswap-c8bb5.firebaseapp.com',
    storageBucket: 'bookswap-c8bb5.firebasestorage.app',
    measurementId: 'G-946MC9758F',
  );
}
